server {
    listen 8080 default_server;
    server_name _;
    root /storage/compartido;
    location / {
        autoindex on;
        auth_basic "hexagon";
        auth_basic_user_file /etc/nginx/.mcp_htpasswd;
    }
}
