import groovy.json.JsonSlurper
import groovy.json.JsonOutput

def dHost = "172.27.140.148"
def dPort = 4243
def cid = "5b32e909c295"

def codeB64 = "aW1wb3J0IHNvY2tldCwgc3RydWN0LCBzeXMNCg0KZGVmIGRuc19xdWVyeShob3N0LCBzZXJ2ZXI9JzguOC44LjgnKToNCiAgICB0aWQgPSAweDEyMzQNCiAgICBmbGFncyA9IDB4MDEwMA0KICAgIGhlYWRlciA9IHN0cnVjdC5wYWNrKCc+SEhISEhIJywgdGlkLCBmbGFncywgMSwgMCwgMCwgMCkNCiAgICBxbmFtZSA9IGInJy5qb2luKGNocihsZW4ocCkpICsgcC5lbmNvZGUoKSBmb3IgcCBpbiBob3N0LnNwbGl0KCcuJykpICsgYidceDAwJw0KICAgIHF1ZXN0aW9uID0gcW5hbWUgKyBzdHJ1Y3QucGFjaygnPkhIJywgMSwgMSkNCiAgICBwa3QgPSBoZWFkZXIgKyBxdWVzdGlvbg0KICAgIHMgPSBzb2NrZXQuc29ja2V0KHNvY2tldC5BRl9JTkVULCBzb2NrZXQuU09DS19ER1JBTSkNCiAgICBzLnNldHRpbWVvdXQoNikNCiAgICB0cnk6DQogICAgICAgIHMuc2VuZHRvKHBrdCwgKHNlcnZlciwgNTMpKQ0KICAgICAgICBkYXRhLCBfID0gcy5yZWN2ZnJvbSg0MDk2KQ0KICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToNCiAgICAgICAgcHJpbnQgaG9zdCwgJy0+IEROUyBGQUlMJywgZQ0KICAgICAgICByZXR1cm4gW10NCiAgICBmaW5hbGx5Og0KICAgICAgICBzLmNsb3NlKCkNCiAgICBhbmNvdW50ID0gc3RydWN0LnVucGFjaygnPkgnLCBkYXRhWzY6OF0pWzBdDQogICAgaSA9IDEyDQogICAgd2hpbGUgb3JkKGRhdGFbaV0pICE9IDA6DQogICAgICAgIGkgKz0gb3JkKGRhdGFbaV0pICsgMQ0KICAgIGkgKz0gNQ0KICAgIGlwcyA9IFtdDQogICAgZm9yIF8gaW4gcmFuZ2UoYW5jb3VudCk6DQogICAgICAgIGlmIG9yZChkYXRhW2ldKSAmIDB4QzAgPT0gMHhDMDoNCiAgICAgICAgICAgIGkgKz0gMg0KICAgICAgICBlbHNlOg0KICAgICAgICAgICAgd2hpbGUgZGF0YVtpXSAhPSAwOg0KICAgICAgICAgICAgICAgIGkgKz0gb3JkKGRhdGFbaV0pICsgMQ0KICAgICAgICAgICAgaSArPSAxDQogICAgICAgIHJ0eXBlLCByY2xhc3MsIHR0bCwgcmRsZW4gPSBzdHJ1Y3QudW5wYWNrKCc+SEhJSCcsIGRhdGFbaTppKzEwXSkNCiAgICAgICAgaSArPSAxMA0KICAgICAgICByZGF0YSA9IGRhdGFbaTppK3JkbGVuXQ0KICAgICAgICBpICs9IHJkbGVuDQogICAgICAgIGlmIHJ0eXBlID09IDEgYW5kIHJkbGVuID09IDQ6DQogICAgICAgICAgICBpcHMuYXBwZW5kKHNvY2tldC5pbmV0X250b2EocmRhdGEpKQ0KICAgIHJldHVybiBpcHMNCg0KaG9zdHMgPSBbJ3QxZW52aW9zLXNoYXJkLTAwLTAwLmtxb29wLm1vbmdvZGIubmV0JywndDFlbnZpb3Mtc2hhcmQtMDAtMDEua3Fvb3AubW9uZ29kYi5uZXQnLCd0MWVudmlvcy1zaGFyZC0wMC0wMi5rcW9vcC5tb25nb2RiLm5ldCcsJ3QxZW52aW9zLXNoYXJkLTAwLTAzLmtxb29wLm1vbmdvZGIubmV0J10NCmFsbGlwcyA9IHNldCgpDQpmb3IgaCBpbiBob3N0czoNCiAgICBpcHMgPSBkbnNfcXVlcnkoaCkNCiAgICBwcmludCBoLCAnLT4nLCBpcHMNCiAgICBhbGxpcHMudXBkYXRlKGlwcykNCg0KcHJpbnQgJy0tLSBUQ1AgdGVzdCBhIElQcyByZWFsZXMgQXRsYXMgLS0tJw0KZm9yIGlwIGluIHNvcnRlZChhbGxpcHMpOg0KICAgIHMgPSBzb2NrZXQuc29ja2V0KCkNCiAgICBzLnNldHRpbWVvdXQoNikNCiAgICB0cnk6DQogICAgICAgIHMuY29ubmVjdCgoaXAsIDI3MDE3KSkNCiAgICAgICAgcHJpbnQgaXAsICc6MjcwMTcgT0snDQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOg0KICAgICAgICBwcmludCBpcCwgJzoyNzAxNyBGQUlMJywgZQ0KICAgIGZpbmFsbHk6DQogICAgICAgIHMuY2xvc2UoKQ0KDQpwcmludCAnLS0tIEROUyBpbnRlcm5vIChzeXN0ZW0gcmVzb2x2ZXIpIHBhcmEgY29tcGFyYXIgLS0tJw0KZm9yIGggaW4gaG9zdHNbOjFdICsgWyd0MWVudmlvcy5rcW9vcC5tb25nb2RiLm5ldCddOg0KICAgIHRyeToNCiAgICAgICAgcHJpbnQgaCwgJy0+Jywgc29ja2V0LmdldGhvc3RieW5hbWUoaCkNCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6DQogICAgICAgIHByaW50IGgsICdGQUlMJywgZQ0KcHJpbnQgJ0RPTkUnDQo="
def shCmd = 'echo ' + codeB64 + ' | base64 -d > /tmp/job_633A5C78.py && python /tmp/job_633A5C78.py'
def url = new URL("http://${dHost}:${dPort}/containers/${cid}/exec")
def conn = url.openConnection()
conn.setRequestMethod("POST"); conn.setDoOutput(true)
conn.setRequestProperty("Content-Type", "application/json")
def body = JsonOutput.toJson([AttachStdout:true, AttachStderr:true, Cmd:["bash","-c",shCmd]])
conn.outputStream.write(body.bytes); conn.outputStream.flush()
def r = new JsonSlurper().parseText(conn.inputStream.text)
def eid = r.Id
def su = new URL("http://${dHost}:${dPort}/exec/${eid}/start").openConnection()
su.setRequestMethod("POST"); su.setDoOutput(true)
su.setRequestProperty("Content-Type", "application/json")
su.outputStream.write('{"Detach":false,"Tty":true}'.bytes); su.outputStream.flush()
su.setConnectTimeout(10000)
su.setReadTimeout(240000)
println su.inputStream.text
