

spring.application.name=DmnSeFdxTrack
logging.file.name=/var/log/java/DmnSeFdxTrack.log
#comentar para produccion el puerto
#server.port=8085

#conexion a mongo
# DEV
#spring.data.mongodb.uri=mongodb://appcsfedex:F3D3V1u64RD0c5@172.26.84.132:27020,172.26.84.132:27021/tracking?replicaSet=rs0
#spring.data.mongodb.uri=mongodb://${MONGO_USER_FDX_SE}:${MONGO_PASS_FDX_SE}@${MONGO_URI_FDX_SE}/${MONGO_DB_NAME_FDX_SE}?replicaSet=${MONGO_DB_REPLICASET_FDX_SE}

# PROD
spring.data.mongodb.uri=mongodb://${MONGO_USER_FDX_SE}:${MONGO_PASS_FDX_SE}@${MONGO_URI_FDX_SE}/${MONGO_DB_NAME_FDX_SE}?replicaSet=${MONGO_DB_REPLICASET_FDX_SE}

#conexion a Mysql
# DEV
#spring.datasource.url= jdbc:mysql://172.27.141.26:3322/claro_envios?useSSL=false&serverTimezone=America/Mexico_City
#spring.datasource.url= jdbc:mysql://${MYSQL_IP_FDX_SE}:${MYSQL_PORT_FDX_SE}/${MYSQL_DB_FDX_SE}?useSSL=false&serverTimezone=America/Mexico_City
#spring.datasource.username=appcsfedex
#spring.datasource.password=F3D3V1u64RD0c[5

# PROD
spring.datasource.url= jdbc:mysql://${MYSQL_IP_FDX_SE}:${MYSQL_PORT_FDX_SE}/${MYSQL_DB_FDX_SE}?useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.username=${MYSQL_USER_FDX_SE}
spring.datasource.password=${MYSQL_PASS_FDX_SE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
#Debbuging
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#server.port = 8005
#spring.profiles.active=http_connection
#comment above profile and uncoment line below to operate using https
spring.profiles.active=https_connection
spring.main.allow-bean-definition-overriding=true

#Variables de restFedex
#DEV
fedex.api.url=https://apis-sandbox.fedex.com
fedex.clientid=l79d65e843b15e4ccb890f6b2a2ff9e9b4
fedex.secretid=f04ae9335a49454e88996f1b57bccc54
#PROD
#fedex.api.url=https://apis.fedex.com
#fedex.clientid=l7d8f0e848e98e419c96821de52c54b516
#fedex.secretid=e5a1bbedbbb9461a8344c772de47d59e
