spring.application.name=DmnSnDhlTrack
logging.file.name=/var/log/java/DmnSnDhlTrack.log
#comentar para produccion el puerto
#server.port=8085

#conexion a mongo
# DEV
#spring.data.mongodb.uri=mongodb://appcsfedex:F3D3V1u64RD0c5@172.26.84.132:27020,172.26.84.132:27021/tracking?replicaSet=rs0
#spring.data.mongodb.uri=mongodb://${MONGO_USER_DHL_SN}:${MONGO_PASS_DHL_SN}@${MONGO_URI_DHL_SN}/${MONGO_DB_NAME_DHL_SN}?replicaSet=${MONGO_DB_REPLICASET_DHL_SN}

# PROD
spring.data.mongodb.uri=mongodb://${MONGO_USER_DHL_SN}:${MONGO_PASS_DHL_SN}@${MONGO_URI_DHL_SN}/${MONGO_DB_NAME_DHL_SN}?replicaSet=${MONGO_DB_REPLICASET_DHL_SN}

#conexion a Mysql
# DEV
#spring.datasource.url= jdbc:mysql://172.27.141.26:3322/claro_envios?useSSL=false&serverTimezone=America/Mexico_City
#spring.datasource.url= jdbc:mysql://${MYSQL_IP_DHL_SN}:${MYSQL_PORT_DHL_SN}/${MYSQL_DB_DHL_SN}?useSSL=false&serverTimezone=America/Mexico_City
#spring.datasource.username=appcsfedex
#spring.datasource.password=F3D3V1u64RD0c[5

# PROD
spring.datasource.url= jdbc:mysql://${MYSQL_IP_DHL_SN}:${MYSQL_PORT_DHL_SN}/${MYSQL_DB_DHL_SN}?useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.username=${MYSQL_USER_DHL_SN}
spring.datasource.password=${MYSQL_PASS_DHL_SN}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
#Debbuging
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#server.port = 8005
#spring.profiles.active=http_connection
#comment above profile and uncoment line below to operate using https
spring.profiles.active=https_connection
spring.main.allow-bean-definition-overriding=true

