spring.application.name = T1 Guias Masivas
logging.file.name=/var/log/java/t1guiasmasivas.log
#server.port=8080

#MONGO
#spring.data.mongodb.uri=mongodb://${MONGO_USER_T1GM}:${MONGO_PASS_T1GM}@${MONGO_URI_T1GM}/${MONGO_DB_NAME_T1GM}?replicaSet=${MONGO_DB_REPLICASET_T1GM}&connectTimeoutMS=${MONGO_DB_CONNTIMEOUT_T1GM}&minPoolSize=${MONGO_DB_MINPOOLSIZE_T1GM}&maxPoolSize=${MONGO_DB_MAXPOOLSIZE_T1GM}&maxIdleTimeMS=${MONGO_DB_MAXIDLETIMEMS_T1GM}&authSource=tracking
spring.data.mongodb.uri=mongodb://appguiasmasivast1:BCD4TiQzYN<u2.N(@172.26.84.132:27020,172.26.84.132:27021/guias_masivas?replicaSet=rs0
#MYSQL
#spring.datasource.url= jdbc:mysql://${MYSQL_IP_T1GM}:${MYSQL_PORT_T1GM}/${MYSQL_DB_T1GM}?useSSL=false&serverTimezone=America/Mexico_City
#spring.datasource.username=${MYSQL_USER_T1GM}
#spring.datasource.password=${MYSQL_PASS_T1GM}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=info
##
#spring.datasource.hikari.connection-timeout=${MYSQL_CONNTIMEOUT_T1GM}
#spring.datasource.hikari.minimum-idle=${MYSQL_MINIDLE_T1GM}
#spring.datasource.hikari.maximum-pool-size=${MYSQL_MAXPOOLSIZE_T1GM}
#spring.datasource.hikari.idleTimeout=${MYSQL_IDLETIMEOUT_T1GM}


spring.main.allow-bean-definition-overriding=true

spring.jmx.enabled=true

#DEV /LOCAL
#server.port=8081

#172.27.141.26 local 172.27.140.151 dev
spring.datasource.url= jdbc:mysql://172.27.140.151:3322/claro_envios?useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.username=appwebhook
spring.datasource.password=4Ap9w38H0o#kT56j
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug


server.error.include-stacktrace=never

