#oauth.resource:https://api.redpack.com.mx
#oauth.authorize:https://api.redpack.com.mx/oauth/authorize
#oauth.token:https://api.redpack.com.mx/oauth/token
#oauth.resource.greeting:https://api.redpack.com.mx/redpack/trackingByNumber
#oauth.resource.client_greeting:https://api.redpack.com.mx/redpack/trackingByNumber


oauth.resource:https://apiqa.redpack.com.mx:5400/
oauth.authorize:https://apiqa.redpack.com.mx:5400/oauth/authorize
oauth.token:https://apiqa.redpack.com.mx:5400/oauth/token
oauth.resource.greeting:https://apiqa.redpack.com.mx:5400/redpack/trackingByNumber
oauth.resource.client_greeting:https://apiqa.redpack.com.mx:5400/redpack/trackingByNumber