spring.application.name=DmnFallidos
logging.file.name=/var/log/java/DmnFallidos.log
#comentar para produccion el puerto
#server.port=8085

# DEV
#spring.data.mongodb.uri=mongodb://apptrack99:Ap9Tr4CK99Lrfg7y@172.26.84.132:27021/tracking?replicaSet=rs0
#spring.data.mongodb.uri=mongodb://${MONGO_USER_99}:${MONGO_PASS_99}@${MONGO_URI_99}/${MONGO_DB_NAME}?replicaSet=${MONGO_DB_REPLICASET}

# PROD
spring.data.mongodb.uri=mongodb://${MONGO_USER_FAILS}:${MONGO_PASS_FAILS}@${MONGO_URI_FAILS}/${MONGO_DB_NAME}?replicaSet=${MONGO_DB_REPLICASET}

#spring.datasource.url= jdbc:mysql://172.27.141.26:3322/claro_envios?useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.url= jdbc:mysql://${MYSQL_IP_FAILS}:${MYSQL_PORT_FAILS}/${MYSQL_DB_FAILS}?useSSL=false&serverTimezone=America/Mexico_City
#spring.datasource.username=apptrack99
#spring.datasource.password=Cr0N99M1nU7o5S$
spring.datasource.username=${MYSQL_USER_FAILS}
spring.datasource.password=${MYSQL_PASS_FAILS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

#server.port = 8005
#spring.profiles.active=http_connection
#comment above profile and uncoment line below to operate using https
spring.profiles.active=https_connection
spring.main.allow-bean-definition-overriding=true