info.app.name=image-processor
info.app.description=Procesador de imagenes
info.app.version=1.2.0
server.port=${USERVAR_APP_PORT:8080}
db.mongo-user=${USERVAR_MONGO_USER}
db.mongo-host=${USERVAR_MONGO_SERVER_URL}
db.mongo-pass=${USERVAR_MONGO_PASS}
db.mongo-db=${USERVAR_MONGO_DATABASE}
db.mongo-auth=${USERVAR_MONGO_AUTHSOURCE}
db.mongo.replicaset=${USERVAR_MONGO_REPLICASET}


spring.kafka.bootstrap-servers=${USERVAR_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=${USERVAR_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${USERVAR_KAFKA_SASL_MECHANISM}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${USERVAR_KAFKA_USERNAME}" password="${USERVAR_KAFKA_PASSWORD}";
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual

product.topic.iamges=${USERVAR_KAFKA_TOPIC}
product.consumer.groupid=${USERVAR_KAFKA_GROUP_ID}

##Variables para el webclient que hace get de las imagenes:
#valor en milisegundos
webclient.image.connectTimeOut=${USERVAR_WEBCLIENT_IMAGE_CONNECT_TIME_OUT}
#valor en milisegundos
webclient.image.readTimeOut=${USERVAR_WEBCLIENT_IMAGE_READ_TIME_OUT}
#valor entero
webclient.image.numberOfRetry=${USERVAR_WEBCLIENT_IMAGE_NUMBER_OF_RETRY}
#valor en segundos
webclient.image.durationRetryBackOff=${USERVAR_WEBCLIENT_IMAGE_DURATION_RETRY_BACKOFF}

#Variables del resize asignado a la imagen en px:
image.size.width=${USERVAR_IMAGE_SIZE_WIDTH}
image.size.height=${USERVAR_IMAGE_SIZE_HEIGHT}
image.tmp.file.path=${USERVAR_IMAGE_TMP_FILE_PATH}

#Variables para obtener token para servicio de subida de imagenes:
app.file-manager.identity.token.url=${USERVAR_FILE_MANAGER_TOKEN_URL}
app.file-manager.identity.token.clientid=${USERVAR_FILE_MANAGER_TOKEN_CLIENT}
app.file-manager.identity.token.grant=${USERVAR_FILE_MANAGER_TOKEN_GRANT}
app.file-manager.identity.token.password=${USERVAR_FILE_MANAGER_TOKEN_PASSWORD}
app.file-manager.url=${USERVAR_FILE_MANAGER_URL}

management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthz
management.endpoints.web.path-mapping.info=image-processor/info
management.info.env.enabled=true

retry.maxAttempts=5
retry.maxDelay=60000
schedule.cron.token=${USERVAR_SCHEDULE_CRON_TOKEN}