server.port=${USERVAR_PORT:8080}

#management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.health=healthz
#management.endpoints.web.path-mapping.info=info
#management.info.env.enabled=true


#SERVER HANDLE ERROR
#server.error.include-message=always
#server.error.include-binding-errors=always
#server.error.include-stacktrace=never
#server.error.include-exception=true
#logging.level.org.apache.http=error
#logging.level.httpclient.wire=error
#logging.level.org.springframework.web.client.RestTemplate=error

#keycloak
keycloak.realm=${USERVAR_KEYCLOAK_REALM}
keycloak.auth-server-url=${USERVAR_KEYCLOAK_AUTH_SERVER_URL}
keycloak.ssl-required=${USERVAR_KEYCLOAK_SSL_REQUIRED}
keycloak.resource=${USERVAR_KEYCLOAK_RESOURCE}
keycloak.credentials.secret=${USERVAR_KEYCLOAK_CREDENTIALS_SECRET}
#-keycloak.use-resource-role-mappings=true
keycloak.bearer-only=${USERVAR_KEYCLOAK_BEARER_ONLY}
#spring.main.allow-bean-definition-overriding=${USERVAR_SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING}
#URL.KEYCLOCK.API=

#ENPOINT FILE MANAGER
filemanager.repositorio=${USERVAR_FILEMANAGER_REPOSITORIO}
#ENDPOINT CATEGORIAS
mscategorias.endpoint=${USERVAR_MSCATEGORIAS_ENDPOINT}
mscategorias.page_size=${USERVAR_MSCATEGORIAS_ENDPOINT_PAGESIZE}
mscategorias.page=${USERVAR_MSCATEGORIAS_ENDPOINT_PAGE}
mscategorias.match=${USERVAR_MSCATEGORIAS_MATCH_ENDPOINT}
#RUTA DE LA PLANTILLA
platilla.ubicacion=${USERVAR_PLATILLA_UBICACION}
platilla.rango_final_dropdown=${USERVAR_PLATILLA_RANGO_FINAL_DROPDOWN}
#RUTA TEMPORAL PARA DEPOSITAR LA PLANTILLA
temporal_path=${USERVAR_TEMPORAL_PATH}
#CELDA INICIAL DE LA PLANTILLA
platilla.celda_inicial=${USERVAR_PLATILLA_CELDA_INICIAL}
#NOMBRE DE LA BASE DE LA PLANTILLA GENERADA
nombre_base_platilla_generada=${USERVAR_NOMBRE_BASE_PLATILLA_GENERADA}
#SCHEDULE CRON
schedule_cron=0 0 * * * *

spring.data.mongodb.authentication-database=${USERVAR_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
spring.data.mongodb.host=${USERVAR_SPRING_DATA_MONGODB_HOST}
spring.data.mongodb.database=${USERVAR_SPRING_DATA_MONGODB_DATABASE}
spring.data.mongodb.username=${USERVAR_SPRING_DATA_MONGODB_USERNAME}
spring.data.mongodb.password=${USERVAR_SPRING_DATA_MONGODB_PASSWORD}
spring.data.mongodb.replicaset=${USERVAR_SPRING_DATA_MONGODB_REPLICASET}

#spring.lifecycle.timeout-per-shutdown-phase=1200s

#spring.data.mongodb.uri=mongodb://${USERVAR_SPRING_DATA_MONGODB_USERNAME}:${USERVAR_SPRING_DATA_MONGODB_PASSWORD}@${USERVAR_MONGODB_SERVER_URL}/${USERVAR_SPRING_DATA_MONGODB_DATABASE}?authSource=${USERVAR_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}





