quarkus.http.port=8080


#Kafka
kafka.bootstrap.servers=${USERVAR_KAFKA_BOOTSTRAP_SERVERS}
mp.messaging.incoming.ticket.connector=smallrye-kafka
mp.messaging.incoming.ticket.topic=${USERVAR_INCOMING_PRODUCT_TOPIC}
mp.messaging.incoming.ticket.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.ticket.commit-strategy=latest
mp.messaging.incoming.ticket.auto.offset.reset=earliest
mp.messaging.incoming.ticket.failure-strategy=dead-letter-queue
mp.messaging.incoming.ticket.dead-letter-queue.topic=${USERVAR_DEAD_LETTER_QUEUE_TOPIC}
mp.messaging.incoming.ticket.group.id=${USERVAR_KAFKA_GROUP_ID}

mp.messaging.incoming.ticket.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${USERVAR_KAFKA_USERNAME}" password="${USERVAR_KAFKA_PASSWORD}";
mp.messaging.incoming.ticket.security.protocol=SASL_SSL
mp.messaging.incoming.ticket.sasl.mechanism=${USERVAR_SASL_MECHANISM}
mp.messaging.incoming.ticket.ssl.truststore.location=${USERVAR_TRUSTSTORE_LOCATION}
mp.messaging.incoming.ticket.ssl.truststore.password=${USERVAR_TRUSTSTORE_PASSWORD}

#kafka.bootstrap.servers=172.26.84.139:27017
#mp.messaging.incoming.ticket.connector=smallrye-kafka
#mp.messaging.incoming.ticket.topic=pcj2-mongo-full4.products.Ticket
#mp.messaging.incoming.ticket.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#mp.messaging.incoming.ticket.commit-strategy=latest
#mp.messaging.incoming.ticket.auto.offset.reset=earliest
#mp.messaging.incoming.ticket.group.id=${quarkus.uuid}

#MongoDB
#quarkus.mongodb.connection-string=mongodb://localhost:27017
#quarkus.mongodb.database=products
#quarkus.mongodb.credentials.username=myUserAdmin
#quarkus.mongodb.credentials.password=123
#quarkus.mongodb.credentials.auth-source=admin

quarkus.mongodb.connection-string=${USERVAR_MONGODB_CONEXION}
quarkus.mongodb.database=${USERVAR_MONGODB_DATABASE}
quarkus.mongodb.credentials.username=${USERVAR_MONGODB_USER}
quarkus.mongodb.credentials.password=${USERVAR_MONGODB_PASS}
quarkus.mongodb.credentials.auth-source=${USERVAR_MONGODB_AUTH}

quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=${USERVAR_CONFIG_APP_QUARKUS_LOG_HANDLER_GELF_HOST}
quarkus.log.handler.gelf.port=${USERVAR_CONFIG_APP_QUARKUS_LOG_HANDLER_GELF_PORT}
quarkus.log.handler.gelf.additional-field."originHost".value=viena-batch-processor

quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.log.handler.gelf.level=${USERVAR_CONFIG_APP_QUARKUS_LOG_APP}

quarkus.health.extensions.enabled=true
quarkus.smallrye-health.root-path=/healthz

version.app=1.1.14
