server.port=${USERVAR_SERVER_PORT:8080}
proyecto.nombre=${USERVAR_PROYECTO_NOMBRE}
info.app.version=1.0.7

management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthz
server.shutdown=graceful

spring.kafka.consumer.bootstrap-servers=${USERVAR_SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${USERVAR_SPRING_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${USERVAR_SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
spring.kafka.listener.poll-timeout=${USERVAR_SPRING_KAFKA_LISTENER_POLL_TIMEOUT}

spring.kafka.properties.security.protocol=${USERVAR_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${USERVAR_KAFKA_SASL_MECHANISM}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${USERVAR_KAFKA_USERNAME}" password="${USERVAR_KAFKA_PASSWORD}";


kafka.topic.name=${USERVAR_KAFKA_TOPIC}
spring.kafka.consumer.properties.spring.json.trusted.packages=com.claroshop.beirut.kafka.dto
spring.data.mongodb.authentication-database=${USERVAR_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
spring.data.mongodb.host=${USERVAR_SPRING_DATA_MONGODB_HOST}
spring.data.mongodb.database=${USERVAR_SPRING_DATA_MONGODB_DATABASE}
spring.data.mongodb.username=${USERVAR_SPRING_DATA_MONGODB_USERNAME}
spring.data.mongodb.password=${USERVAR_SPRING_DATA_MONGODB_PASSWORD}
logging.level.root=info
logging.level.com.example.demo=debug



threads.tail-pool-live=60
threads.max-pool-live=40
threads.core-pool-live=19

published.url.cs=${USERVAR_PUBLISHED_URL_CS}
published.url.sr=${USERVAR_PUBLISHED_URL_SR}




