server.port=${USERVAR_APP_PORT:8080}

spring.kafka.bootstrap-servers=${USERVAR_KAFKA_HOSTANDPORT}
#spring.kafka.ssl.trust-store-location=${USERVAR_KAFKA_TRUSTSTORE_LOCATION}
#spring.kafka.ssl.trust-store-password=${USERVAR_KAFKA_TRUSTSTORE_PASSWORD}
spring.kafka.properties.security.protocol=${USERVAR_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${USERVAR_KAFKA_SASL_MECHANISM}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${USERVAR_KAFKA_USERNAME}" password="${USERVAR_KAFKA_PASSWORD}";
spring.kafka.consumer.auto-offset-reset=latest

kafka.ticket.topic.pending=${USERVAR_TOPIC_TICKET_PENDING}
kafka.ticket.consumer.groupid=${USERVAR_KAFKA_GROUP_ID}

db.mongo-user=${USERVAR_MONGO_USER}
db.mongo-host=${USERVAR_MONGO_HOST}
db.mongo-pass=${USERVAR_MONGO_PASS}
db.mongo-db=${USERVAR_MONGO_DB}
db.mongo-auth=${USERVAR_MONGO_AUTH}


management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthz
